### ISSUE TITLE
FR7: Navigation bar

### ISSUE THREAD

**Issue by jchunduri35** [WSU-4110/ServCity#2]
Goal: This application will have a universal navigation bar with home, automotive, handyman, and landscape. 

Stakeholders: User using our app to find a service nearby 

Description: The navigation bar will be designed to be universally displayed on all pages. It will consist of pages such as automotive, handyman, and landscape. A click on the logo will take the user back to the home page. 

Origin: Based on the project description, the team came up with the idea of building a website which has a navigation bar during our second meeting.

Version: 1.0  
Date: 09/13/2022 
Priority: 2

**Comment by pollchowdhury** [comment]
This has been implemented to our project.
