### ISSUE TITLE
NFR3: Getting information from API 

### ISSUE THREAD

**Issue by jchunduri35** [WSU-4110/ServCity#3]
Goal: To create the user interface with a fully componentized home, automotive, handyman, and landscape pages. This website should be smooth and clean.

Stakeholders: User using our app to find a service nearby 

Description: When the user is using the website, the user should be able to move through the whole site with no issues. The home page should have a nav bar, service options and footer. The automotive service page should have all the working components that help the user with their specific service. The handyman and landscape pages should be working but not complete.

Origin: Based on the project description, the team came up with the idea of building a website which has a navigation bar during our second meeting.

Version: 1.0
Date: 9/15/2022
Priority: 1

**Comment by pollchowdhury** [comment]
This feature has been implemented
